<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Masa.Blazor" Version="1.11.9" />
    <PackageReference Include="Masa.Blazor.MobileComponents" Version="1.11.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinanceTracker.Core\FinanceTracker.Core.csproj" />
    <ProjectReference Include="..\FinanceTracker.Shared\FinanceTracker.Shared.csproj" />
  </ItemGroup>

</Project>
