<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FinanceTracker.Core\FinanceTracker.Core.csproj" />
    <ProjectReference Include="..\..\src\FinanceTracker.Infrastructure\FinanceTracker.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\FinanceTracker.Web\FinanceTracker.Web.csproj" />
    <ProjectReference Include="..\..\src\FinanceTracker.Infrastructure.Sqlite\FinanceTracker.Infrastructure.Sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Masa.Blazor" Version="1.11.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
  </ItemGroup>

</Project>
